version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - ERP_API_KEY=${ERP_API_KEY}
      - GSTN_API_KEY=${GSTN_API_KEY}
      - DOCUMENT_API_KEY=${DOCUMENT_API_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
